package entidades;
// Generated 20/01/2011 02:34:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private Integer id;
     private Double saldo;
     private Date fechaApertura;

    public Cuentas() {
    }

    public Cuentas(Double saldo, Date fechaApertura) {
       this.saldo = saldo;
       this.fechaApertura = fechaApertura;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public Date getFechaApertura() {
        return this.fechaApertura;
    }
    
    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }




}


