package entidades;
// Generated 20/01/2011 02:34:19 by Hibernate Tools 3.2.1.GA



/**
 * CuentasTitularesId generated by hbm2java
 */
public class CuentasTitularesId  implements java.io.Serializable {


     private int idTitulares;
     private int idCuentas;

    public CuentasTitularesId() {
    }

    public CuentasTitularesId(int idTitulares, int idCuentas) {
       this.idTitulares = idTitulares;
       this.idCuentas = idCuentas;
    }
   
    public int getIdTitulares() {
        return this.idTitulares;
    }
    
    public void setIdTitulares(int idTitulares) {
        this.idTitulares = idTitulares;
    }
    public int getIdCuentas() {
        return this.idCuentas;
    }
    
    public void setIdCuentas(int idCuentas) {
        this.idCuentas = idCuentas;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CuentasTitularesId) ) return false;
		 CuentasTitularesId castOther = ( CuentasTitularesId ) other; 
         
		 return (this.getIdTitulares()==castOther.getIdTitulares())
 && (this.getIdCuentas()==castOther.getIdCuentas());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTitulares();
         result = 37 * result + this.getIdCuentas();
         return result;
   }   


}


