package entidades;
// Generated 20/01/2011 02:34:19 by Hibernate Tools 3.2.1.GA



/**
 * CuentasTitulares generated by hbm2java
 */
public class CuentasTitulares  implements java.io.Serializable {


     private CuentasTitularesId id;

    public CuentasTitulares() {
    }

    public CuentasTitulares(CuentasTitularesId id) {
       this.id = id;
    }
   
    public CuentasTitularesId getId() {
        return this.id;
    }
    
    public void setId(CuentasTitularesId id) {
        this.id = id;
    }




}


