package entidades;
// Generated 20/01/2011 02:34:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Titulares generated by hbm2java
 */
public class Titulares  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private Integer dni;
     private Date fechaNac;
     private String domicilio;

    public Titulares() {
    }

    public Titulares(String nombre, String apellido, Integer dni, Date fechaNac, String domicilio) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaNac = fechaNac;
       this.domicilio = domicilio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }




}


